from django.urls import path

from django.contrib.auth import views as auth_views

from main.forms import AdministrateurForm
from . import views

urlpatterns = [
    path('s/', views.home_superadmin, name="home_superadmin"),
    path('s/alladmin/', views.all_administrateur, name="all_administrateur"),
    path('s/listadmin/', views.list_administrateur, name="list_administrateur"),
    path('s/listadmin/update/<str:pk>/', views.update_administrateur, name="update_administrateur"),
    path('s/listadmin/delete/<str:pk>/', views.delete_administrateur, name="delete_administrateur"),
    path('s/listetablissement/', views.list_etablissement, name="list_etablissement"),
    path('s/listetablissement/update/<str:pk>', views.update_etablissement, name="update_etablissement"),
    path('s/listetablissement/delete/<str:pk>', views.delete_etablissement, name="delete_etablissement"),
    path('s/addetab', views.CreateEtablissement, name="add_etablissement"),
    path('a/', views.home_admin, name="home_admin"),
    path('a/chat/',views.lobby,name ="lobby"),
    path('a/profile', views.Profile_Admin, name="profile_admin"),
    path('a/listeval', views.test_evaluateur,name="list_eval"),
    path('a/updateeval/<str:pk>',views.update_evaluateur, name="update_evaluateur"),
    path('a/deleteeval/<str:pk>',views.deleteEvaluateur, name="delete_evaluateur"),
    path('a/addeval',views.CreateEvaluateur,name="add_evaluateur"),
    path('a/allcandidat', views.all_candidat, name="all_candidat"),
    path('a/listcandidat', views.list_candidat, name="list_candidat"),
    path('a/updatecandidat/<str:pk>',views.update_candidat, name="update_candidat"),
    path('a/deletecandidat/<str:pk>',views.deleteCandidat, name="delete_candidat"),
    path('a/allmodule',views.all_module,name="all_module"),
    path('a/listmodule',views.list_module,name="list_module"),
    path('a/updatemodule/<str:pk>',views.update_module, name="update_module"),
    path('a/deletemodule/<str:pk>',views.deleteModule, name="delete_module"),
    path('a/addmodule',views.CreateModule,name="add_module"),
    path('a/listgroupe',views.list_groupe,name="list_groupe"),
    path('a/updategroupe/<str:pk>',views.update_groupe, name="update_groupe"),
    path('a/deletegroupe/<str:pk>',views.deleteGroupe, name="delete_groupe"),
    path('a/allgroupe/', views.all_groupe, name="all_groupe"),
    path('a/addgroupe/',views.CreateGroupe,name="add_groupe"),
    path('a/allgroupe/<str:pk>', views.home_groupe, name="home_groupe"),
    path('a/allgroupe/<str:pk>/listmodule', views.list_module_groupe, name="module_groupe"),
    path('e/', views.home_Evaluateur, name="home_evaluateur"),
    path('e/profile/', views.Profile_Evaluateur, name="profile_evaluateur"),
    path('e/listquestion/',views.list_question,name="list_question"),
    path('e/module/<str:pk1>/questionlist/update/<str:pk>/',views.update_question, name="update_question"),
    path('e/deletequestion/<str:pk>/',views.deleteQuestion, name="delete_question"),
    path('e/deletequestionn/<str:pk>/',views.deleteQuestion2, name="delete_question1"),
    path('e/addquestion/',views.CreateQuestion,name="add_question"),
    path('e/module', views.all_moduleEval, name="allmodule_eval"),
    path('e/module/<str:pk>', views.home_module, name="module_eval"),
    path('e/module/<str:pk>/questionlist/', views.list_question_module, name="listqmod"),
    path('e/module/<str:pk>/questionlist/add2/',views.AddQuestion,name="add_question3"),
    path('e/module/<str:pk>/questionnairelist/', views.list_questionnaire_module, name="listqsmod"),
    path('e/module/<str:pk>/questionnairelist/add/',views.CreateQuestionnaire,name="add_questionnaire"),
    path('e/module/<str:pk>/questionnairelist/<str:pk1>',views.update_questionnaire, name="update_questionnaire"),
    path('e/module/<str:pk>/questionnairelist/deleteqsmod/<str:pk1>',views.deleteQuestionnaire, name="delete_questionnaire"),
    path('e/module/<str:pk>/testlist', views.list_test_module, name="listtestmod"),
    path('e/module/<str:pk>/testlist/test/<str:pk1>/', views.home_test, name="home_test"),
    path('e/module/<str:pk>/testlist/add',views.CreateTest,name="add_test"),
    path('e/module/<str:pk>/testlist/update/<str:pk1>',views.update_test, name="update_test"),
    path('e/module/<str:pk>/testlist/deleteqsmod/<str:pk1>',views.deleteTest, name="delete_test"),
    path('e/module/<str:pk>/testlist/invitation/<str:pk1>',views.Inviter_Candidat, name="inviter_test"),
    path('e/module/<str:pk>/testlist/deleteinvitation/<str:pk1>',views.Delete_Invitation, name="delete_invitation"),
    path('e/module/<str:pk>/testlist/results/<str:pk1>',views.Resultat_test_Evaluateur, name="resultat_test_evaluateur"),
    path('e/module/<str:pk>/testlist/results/<str:pk1>/copie/<str:pk2>',views.ResultatTestCopieEval, name="copie_candidat"),
    path('c/', views.home_Candidat, name="home_candidat"),
    path('c/profile', views.Profile_Candidat, name="profile_candidat"),
    path('c/mytests', views.list_test_candidat, name="my_tests"),
    path('c/mytests/enattente/<str:pk>', views.Test_AttenteConfirmation, name="Test_EnAttente"),
    path('c/mytests/preptest/<str:pk>', views.Pret_PasserTest, name="Prep_Test"),
    path('c/mytests/resultat/<str:pk>', views.ResultatTest, name="Resultat_Test"),
    path('c/mytests/resultat/<str:pk>/copie', views.ResultatTestCopie, name="Resultat_TestCopie"),
    path('passertest/<str:pk>',views.PasserTest,name="passertest"),
    path('login/', views.user_login,name='login'),
    path('logout/', views.logoutUser,name='logout'),
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name="main/user/forgot-password.html"),name="reset_password"),
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name="main/user/reset-passwordsent.html"),name="password_reset_done"),
    path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name="reset-password-form.html"),name="password_reset_confirm"),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name="main/user/reset-password-complete.html"),name="password_reset_complete"),
    path('register/',views.user_register,name='register'),
    path('registerAdmin/',views.add_Admin,name='registeradmin'),
    path('abase',views.base_admin,name="base_admin"),
    path('testqst',views.QuestionnaireListView.as_view(),name='main-view'),
    path('testqst/<pk>/',views.Questionnaire_View,name='quiz-view'),
    path('testqst/<pk>/save/',views.save_quiz_view,name='save-view'),
    path('testqst/<pk>/data/',views.Questionnaire_data_view,name='quiz-data-view'),
  
    



]