# Generated by Django 4.0.4 on 2022-05-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_candidat_groupe_module_question_questionnaire_test_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='etablissement',
            new_name='evaluateur',
        ),
    ]
