# Generated by Django 4.0.4 on 2022-05-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_questionnaire_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reponse',
            old_name='contenu',
            new_name='contenurep',
        ),
    ]
