# Generated by Django 4.0.4 on 2022-05-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_contenu_reponse_contenurep'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reponse',
        ),
    ]
