# Generated by Django 4.0.4 on 2022-05-13 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_questionnaire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.etablissement'),
        ),
    ]
