# Generated by Django 4.0.4 on 2022-05-13 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_candidat_etablissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='etablissement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.etablissement'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='groupe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.groupe'),
        ),
    ]
