# Generated by Django 4.0.4 on 2022-05-13 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_candidat_etablissement_alter_candidat_groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.groupe'),
        ),
    ]
