# Generated by Django 4.0.4 on 2022-05-13 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_candidat_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='etablissement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.etablissement'),
        ),
    ]
