# Generated by Django 4.0.4 on 2022-05-14 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_groupe_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='etablissement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.etablissement'),
        ),
        migrations.AlterField(
            model_name='module',
            name='evaluateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.evaluateur'),
        ),
        migrations.AlterField(
            model_name='module',
            name='groupes',
            field=models.ManyToManyField(blank=True, to='main.groupe'),
        ),
    ]
