# Generated by Django 4.0.4 on 2022-05-17 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_resultat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='module',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.module'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100)),
                ('status', models.IntegerField(blank=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.candidat')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.test')),
            ],
        ),
    ]
