# Generated by Django 4.0.4 on 2022-05-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_invitation_candidat_alter_invitation_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
