# Generated by Django 4.0.4 on 2022-05-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_invitation_code_alter_invitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluateur',
            name='isValide',
            field=models.BooleanField(default=False),
        ),
    ]
