# Generated by Django 4.0.4 on 2022-05-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_question_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluateur',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
