# Generated by Django 4.0.4 on 2022-05-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_evaluateur_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='profile_pic',
            field=models.ImageField(blank=True, default='undraw_profile.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='candidat',
            name='profile_pic',
            field=models.ImageField(blank=True, default='undraw_profile.svg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='evaluateur',
            name='profile_pic',
            field=models.ImageField(blank=True, default='undraw_profile.svg', null=True, upload_to=''),
        ),
    ]
