# Generated by Django 4.0.4 on 2022-05-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_resultat_copie'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('QCM', 'QCM'), ('QCS', 'QCS')], default='QCM', max_length=100),
        ),
    ]
