# Generated by Django 4.0.4 on 2022-05-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
